# Generated by Django 5.0.6 on 2026-06-16 10:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_coa', '0002_initial'),
        ('company', '0002_initial'),
        ('journal', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name_en', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('STOCK', 'Stock item'), ('SERVICE', 'Service')], default='STOCK', max_length=8)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('unit', models.CharField(default='pcs', max_length=24)),
                ('sale_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('average_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('is_active', models.BooleanField(default=True)),
                ('cogs_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts_coa.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inventory_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts_coa.account')),
                ('sales_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts_coa.account')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.taxrate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_no', models.CharField(max_length=30, unique=True)),
                ('date', models.DateField()),
                ('direction', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=3)),
                ('reason', models.CharField(choices=[('OPENING', 'Opening balance'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale / Issue'), ('ADJUSTMENT', 'Adjustment'), ('RETURN', 'Return')], default='ADJUSTMENT', max_length=12)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=16)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('total_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('qty_after', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('avg_cost_after', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=8)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('contra_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts_coa.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='journal.journalentry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
