# Generated by Django 5.0.6 on 2026-06-18 11:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_bulk',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AddField(
            model_name='product',
            name='price_retail',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AddField(
            model_name='product',
            name='price_wholesale',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
    ]
