# Generated by Django 5.0.6 on 2026-06-18 12:02

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_coa', '0002_initial'),
        ('company', '0002_initial'),
        ('inventory', '0003_productsupplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AddField(
            model_name='product',
            name='max_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_selling_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('minimum_selling_price__gte', 0)), name='prod_min_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('cost_price__gte', 0)), name='prod_cost_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('max_discount_percent__gte', 0), ('max_discount_percent__lte', 100)), name='prod_discount_range'),
        ),
    ]
