# Generated by Django 5.0.6 on 2026-06-16 09:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_no', models.CharField(max_length=30, unique=True)),
                ('date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('total', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_no', models.CharField(max_length=30, unique=True)),
                ('supplier_ref', models.CharField(blank=True, max_length=64)),
                ('date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('total', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('line_subtotal', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('line_total', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_no', models.CharField(max_length=30, unique=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
