# Generated by Django 5.0.6 on 2026-06-16 09:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank')], default='CASH', max_length=4)),
                ('bank_name', models.CharField(blank=True, max_length=160)),
                ('account_number', models.CharField(blank=True, max_length=64)),
                ('iban', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_no', models.CharField(max_length=30, unique=True)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer')], max_length=12)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=8)),
                ('memo', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
