# Generated by Django 5.0.6 on 2026-06-16 09:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_no', models.CharField(max_length=30, unique=True)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('total', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('name_ar', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Expense categories',
                'ordering': ['name'],
            },
        ),
    ]
