# Generated by Django 5.0.6 on 2026-06-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=160)),
                ('name_ar', models.CharField(blank=True, max_length=160)),
                ('type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], max_length=10)),
                ('normal_balance', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], editable=False, max_length=6)),
                ('is_postable', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SystemAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('AR', 'Accounts Receivable (control)'), ('AP', 'Accounts Payable (control)'), ('SALES', 'Sales Revenue'), ('SALES_RETURNS', 'Sales Returns'), ('PURCHASES', 'Purchases / Inventory'), ('PURCHASE_RETURNS', 'Purchase Returns'), ('VAT_PAYABLE', 'VAT Payable (output tax)'), ('VAT_RECEIVABLE', 'VAT Receivable (input tax)'), ('CASH', 'Default Cash'), ('RETAINED_EARNINGS', 'Retained Earnings'), ('ROUNDING', 'Rounding differences')], max_length=32, unique=True)),
            ],
        ),
    ]
