# Generated by Django 5.0.6 on 2026-06-16 09:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_no', models.CharField(max_length=30, unique=True)),
                ('entry_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=8)),
                ('memo', models.TextField(blank=True)),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Journal entries',
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('credit', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('line_memo', models.CharField(blank=True, max_length=255)),
                ('is_cleared', models.BooleanField(default=False)),
            ],
        ),
    ]
