# Generated by Django 5.0.6 on 2026-06-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesinvoiceitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='price_tier',
            field=models.CharField(choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale'), ('BULK', 'Bulk')], default='RETAIL', max_length=10),
        ),
    ]
