# Generated by Django 5.0.6 on 2026-06-23 11:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesinvoice_price_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit')], default='CASH', max_length=6),
        ),
    ]
